# Generated by Django 3.2.25 on 2024-07-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240711_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Updated_on',
        ),
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
