# Generated by Django 3.2.25 on 2024-07-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240711_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='category_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='media_type',
        ),
    ]
