# Generated by Django 5.0.7 on 2024-07-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
