# Generated by Django 5.0.7 on 2024-07-26 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_type',
        ),
    ]
